nominal/nominal.py
Previously, datasets could use relative timestamps but the lib would fail if attaching those datasets to a run. Now the runs should be able to utilize datasets with relative or absolute timestamps.
Tested by uploading runs with mixed absolute and relative timestamps.
=> fix: allow for relative timestamps in runs

.github/workflows/deploy-docs.yml
Used a template for mdBook, but edited for mkdocs (the mkdocs actions I found all seemed pretty bad---poor ways to specify dependencies, etc)
=> chore: create deploy-docs.yml

nominal/core.py, poetry.lock, pyproject.toml
simple helper to avoid pitfall of needing to open in binary mode
=> feat: add csv to dataset method

nominal/core.py, nominal/nominal.py
Building off the comments in #38
=> fix: detect .csv.gz and add helper method for initial csv creation

tests/e2e/test_core.py
=> test: add e2e test to update run start/end

nominal/core/run.py
This allows a run to be archived from the client
=> feat: archive run

nominal/__init__.py, nominal/__main__.py, nominal/cli/__init__.py, nominal/cli/attachment.py, nominal/cli/auth.py, nominal/cli/dataset.py, nominal/cli/run.py, nominal/cli/util/global_decorators.py, nominal/core/__init__.py, nominal/core/_clientsbunch.py, nominal/core/_conjure_utils.py, nominal/core/_multipart.py, nominal/core/_utils.py, nominal/core/attachment.py, nominal/core/channel.py, nominal/core/checklist.py, nominal/core/client.py, nominal/core/dataset.py, nominal/core/log.py, nominal/core/run.py, nominal/core/unit.py, nominal/core/user.py, nominal/core/video.py, nominal/nominal.py, nominal/ts.py, tests/e2e/test_core.py, tests/e2e/test_toplevel.py
=> chore: absolute imports

.coveragerc, justfile, nominal/core/dataset.py, poetry.lock, pyproject.toml, tests/cli/test_auth.py, tests/core/test_dataset.py
* coveragerc
* test structure
* some testing in cli and core
* caught a bug :)
=> fix: early return in set_units, add coverage + unit tests

nominal/core/_clientsbunch.py, nominal/core/channel.py, nominal/core/client.py, nominal/core/connection.py, nominal/core/dataset.py, nominal/ts.py
- add `NominalClient.get_connection()`
- add `Connection.get_channel()`
- add start/end parameters to `Channel.to_pandas()`
=> feat: add connections

docs/reference/toplevel.md, nominal/__init__.py, nominal/core/__init__.py
this should add them to the docs as well
=> feat: add Channel and Connection to top level

nominal/core/client.py, nominal/nominal.py
=> feat: allow end=None when creating runs for streaming

nominal/core/video.py
Allows end users to archive / unarchive videos, hiding / revealing them in the 'All Videos' page respectively.
=> feat: allow archiving / unarchiving videos

nominal/core/_clientsbunch.py, nominal/core/channel.py, nominal/core/dataset.py
=> feat: add method to get decimated data to Channel

nominal/core/_clientsbunch.py, nominal/core/client.py, nominal/nominal.py
=> feat: add create streaming connection

nominal/core/__init__.py, nominal/core/_clientsbunch.py, nominal/core/client.py, nominal/core/workbook.py, nominal/nominal.py
=> feat: add function to create workbook from template

nominal/core/run.py
=> feat: remove data sources from run

docs/reference/toplevel.md, nominal/__init__.py, nominal/core/__init__.py, nominal/core/_clientsbunch.py, nominal/core/asset.py, nominal/core/client.py, nominal/nominal.py
=> feat: add create/get asset

docs/index.md
=> link back to docs.nominal.io

docs/css/slate-muted.css
=> on-brand-colors

nominal/core/stream.py
Allow users to stream a sequence of value+timestamp pairs at a time to prevent calls to acquiring the batch lock in high frequency contexts
=> feat: add enqueue_batch to NominalWriteStream

nominal/core/_clientsbunch.py, nominal/core/_multipart.py, nominal/core/client.py, nominal/core/dataset.py
Revert "feat: propagate requests.Session with cert file (#139)"
This reverts commit efdf843065602f70fb615038e759a2a524439361.
=> fix: nm.upload_pandas() fails with SSLError

nominal/__init__.py
allows using `nm.upload_mcap_video` to call the function
=> feat: export upload_mcap_video function

nominal/core/asset.py, nominal/core/client.py, nominal/core/run.py, nominal/nominal.py
=> feat: add support for tags in connections, runs and assets

nominal/__init__.py, nominal/core/run.py, tests/e2e/test_core.py
Expose the ability to add an asset to a run.
=> feat: add run.add_asset()

nominal/_api/scout_service_api/__init__.py, nominal/_api/scout_service_api/_impl.py, nominal/_api/scout_service_api/event/__init__.py, nominal/_api/scout_service_api/openapi/__init__.py, nominal/_api/scout_service_api/scout_internal_search_api/__init__.py
=> feat: bump conjure definitions

nominal/core/checklist.py, nominal/core/client.py, nominal/core/data_review.py, nominal/core/filetype.py, pyproject.toml, uv.lock
Example:
```py
from nominal import NominalClient
from getpass import getpass
client = NominalClient.create("https://api.gov.nominal.io/api", getpass())
dataset = client.create_ardupilot_dataflash_dataset("dataflash.bin", None)
print("created dataset", dataset.nominal_url)
dataset.poll_until_ingestion_completed()
print("ingestion completed", dataset.rid)
```
=> feat: add ardupilot dataflash ingest

nominal/core/_conjure_utils.py, nominal/core/asset.py, nominal/core/run.py
=> feat: add links to Run.update and Asset.update

nominal/core/_conjure_utils.py, nominal/core/client.py, pyproject.toml, uv.lock
=> feat: bump nominal api to 0.565.1

nominal/core/run.py
=> feat: expose run `asset` field

nominal/core/client.py, nominal/core/filetype.py, nominal/nominal.py, pyproject.toml, uv.lock
=> feat: add support for journal json upload

nominal/core/client.py, nominal/core/dataset.py
=> feat: support multi-file dataflash datasets

nominal/core/video.py
=> feat: update docs to reflect h265 support

nominal/core/client.py, pyproject.toml, uv.lock
=> feat: plumb channel prefix for tabular files

nominal/core/dataset.py, uv.lock
=> feat: use filename for new files when adding data to dataset for csv/parquet

nominal/core/dataset.py
=> feat: add data from mcap io

nominal/core/asset.py, uv.lock
=> fix: fix nondeterminism in asset list_datasets

nominal/core/dataset.py
=> feat: plumb column tag keys

nominal/core/write_stream_base.py, nominal/experimental/stream_v2/_write_stream.py
Expose tags to the `enqueue_from_dict` streaming function
=> feat: expose tags to enqueue_from_dict

nominal/core/dataset.py, pyproject.toml, uv.lock
=> feat: tag columns mapping

nominal/core/_conjure_utils.py, nominal/core/channel.py, nominal/core/client.py, nominal/core/datasource.py, pyproject.toml, uv.lock
=> feat: bump version to fix workbook templates

nominal/core/_networking.py, uv.lock
=> feat: retry read and connection errors

nominal/core/dataset.py
=> fix: properly check filetype for warning

pyproject.toml
=> feat: bump nominal-api-protos version when installing nominal[protos]

pyproject.toml, uv.lock
No code in the client depends on this at all
=> fix: remove hdf5 dependency group

nominal/core/_utils/pagination_tools.py
=> fix: pagination in search_users would infinitely loop with sufficient users

nominal/core/_utils/__init__.py, nominal/core/_utils/pagination_tools.py, nominal/core/_utils/query_tools.py, nominal/core/client.py
=> feat: allow searching datasets

nominal/core/event.py
=> feat: add labels to event class

tests/core/test_dataset.py, tests/test_iterator_tools.py
=> chore: add batch tests for Dataset.write_logs

nominal/core/data_review.py
=> fix: make nominal_url for data_review accurate again

README.md
=> chore: new nominal logo in readme
