nominal/nominal.py

You can pass file paths to upload or a list of datasets (where the ref_name is pulled from `dataset.filename`) as before, or a dict mapping the ref_name to the dataset, which becomes the preferred ref_name in the run if it's included.
```python
>>> import nominal as nm
>>> from nominal import Dataset, Run
>>> dataset = Dataset(nm.data.penguins(), "penguins.csv")
>>> r = Run(datasets=[dataset])
>>> r.upload()
Link to Run:
https://app-staging.gov.nominal.io/runs/
<Response [200]>
>>> r = Run(datasets={"test-ref-name": dataset})
>>> r.upload()
Link to Run:
https://app-staging.gov.nominal.io/runs/
<Response [200]>
```
As expected, the first run uploaded has the dataset ref_name "penguins.csv", the dataset filename:
and the second run uploaded has the dataset ref_name "test-ref-name":

feat: add support for dataset ref names in a run

---

nominal/nominal.py
poetry.lock

Adds relative time series support to Dataset and Ingest classes.
Can do things like:
```py
from nominal import Ingest
dataset = Ingest().read(path = '/Users/jp/Desktop/penguins.csv', relative=True, ts_col='Sample Number')
dataset.relative # True
dataset.relative_units # 'SECONDS'
dataset.upload()
```
or 
```py
from nominal import Dataset
df = nm.data.penguins() # some polars dataframe
ds = Dataset(df, relative = True, ts_col = 'Sample Number')
ds.upload()
```

[WIP] Relative time series

---

nominal/nominal.py

Previously, `dataset.upload()` only worked for timezone-naive timestamps. Now we explicitly write all timestamps as timezone-aware and the backend can successfully parse them.

bugfix: use uniform datetime fmt with 8601 type on the wire

---

nominal/sdk.py

We technically support this on the API side, but we want to start with time bounds being required from the lib for now

Make run start_time required [sdk]

---

nominal/sdk.py

- make the filename urlsafe in `add_to_dataset_from_io` as well
- use urllib.parse rather than base64 encoding the filename

hotfix: [sdk] Multifile dataset urlsafe

---

.github/workflows/deploy-docs.yml
justfile

the doc deploy failed, presumably due to using `mkdocs` rather than `poetry run mkdocs`. Added a `just` command for building the docs, and use that in the action. 
Testing: I now realize I can change the workflow to `on: pull_request` to test it on this PR, and then can switch it back to `on: push` before merging! The deployment step failed, but the `build` step succeeded, so I think we're good.

chore: just build-docs

---

docs/reference/nom-cli.md
poetry.lock
pyproject.toml

I fixed a small bug in the `mkdocs-click` package, which allows default args to be shown in the generated docs. This isn't merged yet, but we can pin against my fork until it is.
See the PR here: https://github.com/mkdocs/mkdocs-click/pull/79

chore: click context settings in docs

---

docs/usage/examples.md

Change repeated `start` key typo to `end`

docs: update repeated start typo for Create a Run

---

nominal/_utils.py

Currently, a file path of `some/path/file.new.csv` would fail because it will directly compare against `new.csv`

fix: file path extension check fails for paths with other "."s in them

---

nominal/_utils.py
nominal/core.py
nominal/nominal.py
pyproject.toml
tests/e2e/conftest.py
tests/e2e/test_core.py
tests/e2e/test_toplevel.py

This change renames the parameter `exact_name` to `name_substring` to communicate the intent. This performs an exact (as opposed to fuzzy) substring match on the name.
You should update your code accordingly:
```py
nm.search_runs(exact_name="some_substring")
```
should become
```py
nm.search_runs(name_substring="some_substring")
```
This change is backwards compatible; the old argument "exact_name" is soft-deprecated - it warns, but still works, and will be removed later. Functionality with the new and old argument name is tested, as is the warning.

fix: search_runs parameter rename: exact_name -> name_substring

---

nominal/core.py

and add parametrization
Solves an issue we saw with larger json payloads, where it may take >10s to upload

fix: change default connection timeout to 30s (up from 10s)

---

.github/release-please-config.json

- set `include-component-in-tag: false` ([defaults to true](https://github.com/googleapis/release-please/blob/64ffba96734bf158818121c067870077d903611b/schemas/config.json#L78)) to prevent release-please from searching for `nominal-vX.Y.Z` formatted tags

fix: remove component from release please tag

---

.github/release-please-config.json

I found this note https://github.com/googleapis/release-please/blob/64ffba96734bf158818121c067870077d903611b/docs/manifest-releaser.md?plain=1#L258C9-L260
That package name is required for  python type releases

chore: add package-name to config

---

nominal/cli/util/click_log_handler.py

With our current mypy settings, it is not allowed to inherit from a genericly type-hinted class. HOWEVER, this fails in python <=3.10 with a runtime error that is _not_ found by mypy. The fix is simple-- tell mypy to ignore this line and write code in a version agnostic way

fix: remove subscript type specification for inheritance, not supported in <=3.10

---

nominal/core/channel.py
nominal/core/dataset.py

Given that the rest of the Channel class fails in the presence of Archetype series (preferring instead only to work with logical series), it is best if we don't expose the ability to get archetypical series at all in the client until the backend improves.

feat: hide archetype series from channel abstraction

---

nominal/cli/auth.py

As a new user, i ran into issues where i put in the wrong api for nominal, but since the auth flow didnt throw any issues, I didn't realize. Then, working through the docs examples, i ran into erroneous errors since my auth was misconfigured.
This eagerly checks the auth and url provided so users don't go down the path of and get frustrated.
invalid base_url
invalid token
everything correct

feat: validate login flow for new users

---

justfile
nominal/core/_conjure_utils.py
nominal/core/client.py
tests/e2e/conftest.py

we might want to consider moving this inside the pyproject.toml for some more organization, and adding many of the other supported ruff rules

chore: clean unused imports

---

nominal/core/channel.py

`value in EnumClass` only works on Python 3.12+, we should check `value in EnumClass.__members__` instead for earlier versions!
3.11 gives this information:
```
<stdin>:1: DeprecationWarning: in 3.12 __contains__ will no longer raise TypeError, but will return True or
False depending on whether the value is a member or the value of a member
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/nix/store/kcm5282kss1mnil624lccr7y8wqg75vk-python3-3.11.9/lib/python3.11/enum.py", line 742, in __contains__
raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumType'
```

fix: value in enum classes check for python < 3.12

---

docs/css/slate-muted.css
mkdocs.yml

When viewing the docs, the highlighter-style colors for class, meth, attr, etc are nice disambiguators, but also draw your attention off of the important parts of the text. This is more pronounced and potentially annoying when searching through  the docs with the typical yellow highlights of inline text. So this adds a "muted" version that just falls back to the default text color.
I couldn't figure out how to "inherit" from the slate theme and just change a few values unfortunately, so I just copied the scss file and hardcoded the values which would otherwise computed.

feat(docs): slate-muted color scheme

---

nominal/core/dataset.py
tests/core/test_dataset.py

Removes the need for this antipattern:
```
client = nominal.get_default_client()
dataset = client.create_csv_dataset(...)
dataset.poll_for_io_completion()
dataset = client.get_dataset(dataset.rid)
```
and replace with 
```
client = nominal.get_default_client()
dataset = client.create_csv_dataset(...)
dataset.poll_for_io_completion()
```

feat: make polling for io completion update dataset metadata

---

nominal/_tdms.py
nominal/nominal.py

Previous implementation of upload_tdms() only allowed for waveform data where the time interval property had been set. Not all users use waveforms, regular time series data may just have a time column (a la CSV). This PR adds optional args to upload_tdms() for time column name and type.

feat: adding ability to specify time column in TDMS groups

---

nominal/_utils.py
nominal/cli/attachment.py
nominal/core/__init__.py
nominal/core/_multipart.py
nominal/core/client.py
nominal/core/dataset.py
nominal/core/filetype.py
nominal/nominal.py

Move `FileType` and `FileTypes` from `nominal._utils` to `nominal.core`. To preserve backcompat for a time, a custom module `__getattr__` provides the types at the old path with  a deprecation warning:
```py
>>> from nominal._utils import FileTypes
<stdin>:1: UserWarning: nominal._utils.FileTypes is deprecated and will be removed in a future version, use nominal.core.FileTypes instead.
>>> from nominal._utils import FileType
<stdin>:1: UserWarning: nominal._utils.FileType is deprecated and will be removed in a future version, use nominal.core.FileType instead.
```

feat: make FileType(s) public

---

.github/workflows/lint-pr-title.yml

See https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable

fix: sanitize PR title before use

---

nominal/cli/dataset.py
nominal/core/client.py
nominal/nominal.py

Channel names may have a hierarchical structure, with a delimiter separating the levels. For example, `vehicle.assembly.sensor` is a period-delimited channel name. This change allows users to define the delimiter used in their channel names.

feat: add channel name delimiter to file ingest

---

nominal/__init__.py
nominal/core/client.py
nominal/nominal.py

connection should start with a blank slate of tags.

fix: remove available_tag_values from create streaming connection and expose get connection

---

nominal/core/client.py
nominal/core/run.py
tests/e2e/test_core.py

this PR removes the add_asset endpoint and adds it as an option in create run instead.
The add_asset endpoint is OK to remove because it is currently broken-- it will always fail validation because runs are always associated with an asset by default.

feat: add asset via run creation instead

---

nominal/__init__.py
nominal/cli/__init__.py

There are various ways to do this; this method relies on the distribution version, which means, as a dev, if you have an editable install and the pyproject.toml changes, it won't be picked up. An alternative is to define `__version__` in the `__init__.py`, and to extract it from there. Hatchling [makes that easy](https://hatch.pypa.io/1.9/version/), it's just a matter of taste.

feat: add `nominal.__version__` and `nom --version`

---

nominal/core/connection.py

The low default batch can cause excessive small requests for high rate or high volume data

feat: improve streaming default params

---

nominal/experimental/stream_v2/_serializer.py
nominal/experimental/stream_v2/_write_stream.py

after creating the write stream context manager we do not shutdown cleanly after keyboard interrupt
the goal of this pr is to fix ^

fix: cleanup streaming shutdown

---

nominal/core/client.py
nominal/nominal.py

I noticed that the free function for `create_run` doesn't allow specifying `properties`, `labels`, or `attachments`, although the method defined on the client object does, which means that users have to call `get_default_client` if they want to create a run with any of these values.

feat: expose more parameters in top-level `create_run`

---

nominal/core/asset.py
nominal/core/run.py

- Adds the `list_data_sources` function which, unlike `list_datasets`, fetches all types of sources (Videos, LogSets, Datasets, Connections)
- Fixes a bug whereby LogSets were excluded from removal by `remove_data_sources`
- Allows for a single rid to be passed to `remove_data_sources`:
```
drone.remove_data_sources(
data_sources='ri.data-source.cerulean-staging.log-set.2f768ee8-c071-41b6-8239-73b3686ef7f7'
)
```

fix: list and remove various types of data sources

---

nominal/core/video.py
pyproject.toml
uv.lock

Moves the client off of a bad version dependency

fix: bump nominal api to latest version

---

nominal/_utils.py
nominal/core/dataset.py
uv.lock

dataset.get_channels() was still calling legacy method when no args were passed in.
- update decorator to properly handle this case

fix: dataset get_channels()

---

nominal/_utils.py
nominal/core/client.py
nominal/core/connection.py
nominal/core/stream.py
nominal/nominal.py
nominal/ts.py
tests/e2e/test_toplevel.py

🪓 Removing members, args, etc that have been deprecated (i.e., `UserWarning` with a recommended alternative) for at least 90 days
❌ `nominal._utils.FileType`
✅ `nominal.core.FileType`
❌ `nominal._utils.FileTypes`
✅ `nominal.core.FileTypes`
❌ `nominal.core.NominalWriteStream`
✅ `nominal.core.WriteStream`
❌ `NominalClient.search_runs(exact_name="...")`
✅ `NominalClient.search_runs(name_substring="...")` 
❌ `NominalClient.search_runs(label="label")`
✅ `NominalClient.search_runs(labels=["label"])` 
❌ `NominalClient.search_runs(property=("key", "value"))` 
✅ `NominalClient.search_runs(properties={"key": "value")`
❌ `NominalClient.search_assets(label="label")`
✅ `NominalClient.search_assets(labels=["label"])` 
❌ `NominalClient.search_assets(property=("key", "value"))` 
✅ …

feat: remove 3mo+ deprecations

---

nominal/core/__init__.py
nominal/core/asset.py
nominal/core/client.py
nominal/core/dataset.py
nominal/core/datasource.py
nominal/core/log.py
nominal/core/run.py

Nominal is deprecating the "LogSet" data source type in favor of log channels on any existing or new datasets. As a result, we're deprecating the client lib functions for getting or creating LogSets, and we're adding the ability to stream logs up to Nominal with `datasource.write_logs`. Unlike the previous log set API which needed to serialize the entire log set in a single JSON object, the new API allows for batch writing and can be continuously appended to.
Not yet implemented: reading a log channel.

feat: add log streaming, deprecate LogSets

---

nominal/core/_clientsbunch.py
nominal/core/_multipart.py
nominal/core/asset.py
nominal/core/attachment.py
nominal/core/channel.py
nominal/core/checklist.py
nominal/core/client.py
nominal/core/data_review.py
nominal/core/dataset.py
nominal/core/datasource.py
nominal/core/log.py
nominal/core/run.py
nominal/core/video.py
nominal/core/video_file.py
nominal/core/workbook.py
nominal/experimental/stream_v2/_write_stream.py
pyproject.toml
uv.lock

Subsumes #278 
This PR adds basic support for workspaces. Workspace RIDs (not their name/ID) are specified when you construct the client. All API calls that depend on workspace as a parameter have the workspace passed in. Backwards compatibility is supported as it is in the APIs currently, by leaving the workspace param optional, defaulting to the org's default workspace.
Note that you can only use workspaces with `NominalClient.create(..., workspace_rid)` currently---the global "default" client will have no workspace set.
To find all of the places where workspace _could_ be provided, I generated conjure types locally where I changed all instances of `optional<rids.WorkspaceRid>` to `rids.WorkspaceRid` so the type checker could find them all. After all instances were found, I then fell …

feat: add workspace rids

---

nominal/core/connection.py
tests/test_write_stream.py

Getting tags for a connection have been moved to DataSourceService#getTagValuesForDataSource

chore: remove unused available tags field from connection object

---

pyproject.toml

We should use `==` to avoid weird disconnect state between `nominal-api` and `nominal-client`

fix: tie to a specific version of nominal-api

---

nominal/cli/util/global_decorators.py

Work around it by manually extracting those keywords, and ignoring concerns about assignment (we know click will do its job).
This use-case is not supported by PEP612, although it may be handled in the future.

chore: mypy 1.15 will flag `ParamSpec.args` / `ParamSpec.kwargs` being split

---

justfile
pyproject.toml

I've been running it under 3.13 for a while now without any issues.
3.9 is EOL October 2025, FWIW, around the same time 3.14 is being released.

chore: indicate that client is compatible with Python 3.13

---

pyproject.toml

This avoids MyPy complaining about `def test_foo(): ...` not being annotated with `-> None`.

chore: allow untyped defs in test suite

---

nominal/core/_multipart.py

I noticed that we have a few ruff failures, so will address each of those in a separate PR.
This one prevents overriding the `e` argument to the function the `try/except` clause, also avoiding confusion as to *which* e we are referring to when logging the error.

fix: fix function argument overwrite (propagate exception)

---

nominal/core/dataset.py

Presumably, this warning was for the case where filetype was *neither* parquet or csv for a tabular upload. Right now, it shows up when calling `add_tabular_data` with a CSV file.

fix: remove warning on uploading CSV

---

nominal/experimental/video_processing/video_conversion.py

`anullsrc` won't be recognized if `-f lavfi` flag doesn't occur prior to `-i anullsrc...`.

fix: video conversion when there is no audio

---

nominal/core/client.py
nominal/core/connection.py
nominal/nominal.py

Undoes the parts of #296 that deprecated StreamingConnection. This is on the roadmap but tag support is not yet at parity with datasets, so we'll have both hanging around for a bit longer.

feat: un-deprecate creating streaming connections

---

nominal/experimental/video_processing/video_conversion.py

We used to default to 10s, which is quite far apart, and can easily cause backend segmentation to hit our 20MB segment limit (segmenting a video is lower bounded by the distance between key frames). We change the default to 2s, which should work, but maybe for 4k60fps users will want to set this even lower, to something like 1s.

fix: reduce default key frame interval to 2s

---

nominal/core/video.py

Same as what we did with Dataset, to avoid repeating the classname in function names.

feat: clean up video api

---

nominal/core/client.py
nominal/core/data_review.py

See ticket for more details.
Updates client to not use deprecated fields and move away from CheckViolation in favor of Events.

feat: clean up DataReview API usage

---

nominal/core/event.py

fix: parse event duration nanos

---

README.md
docs/mkdocs.yml
docs/src/index.md
docs/src/reference/toplevel.md

This PR fixes old links to the python quickstart section of our documentation. 
Old link [broken]: https://docs.nominal.io/python/quickstart
New link [current]: https://docs.nominal.io/core/sdk/python-client/quickstart

fix: broken links to python quickstart
